[[mpv]]
arch = "aarch64"
git-tree-sha1 = "8dee61c07712739c8225e7447fb46da185a09c78"
libc = "glibc"
os = "linux"

    [[mpv.download]]
    sha256 = "21ba37502e8b24d6b70cfb95f87b486d417c7ddcac49cdc354d17dbe30a6f7c0"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.aarch64-linux-gnu.tar.gz"
[[mpv]]
arch = "aarch64"
git-tree-sha1 = "d9658fe3ef219a11cdffb60d7461f7444dff3837"
libc = "musl"
os = "linux"

    [[mpv.download]]
    sha256 = "8d345a30bd39b2d86ad4dfadd76c76bb5fc4d313866e616e1397f7dbc0c6db93"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.aarch64-linux-musl.tar.gz"
[[mpv]]
arch = "armv7l"
git-tree-sha1 = "bc05b586f1d6f529d8f1e95642dbdf02f3df5601"
libc = "glibc"
os = "linux"

    [[mpv.download]]
    sha256 = "6076553aafba1278b38239455d1c52892bcb78f336d4ca8f903b461389551ed4"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.armv7l-linux-gnueabihf.tar.gz"
[[mpv]]
arch = "armv7l"
git-tree-sha1 = "69db9fca1eeb02736c4bf0e9ea38ca5b4efa7196"
libc = "musl"
os = "linux"

    [[mpv.download]]
    sha256 = "8fd8e675f191a86ecc889f03cd7de89323d8898ff5d0471cdb2d3b9a121545dd"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.armv7l-linux-musleabihf.tar.gz"
[[mpv]]
arch = "i686"
git-tree-sha1 = "777705e8c9e79a506717fc0e6c70b34c92cbcce4"
libc = "glibc"
os = "linux"

    [[mpv.download]]
    sha256 = "53b4b1d021de0dde3493865ebcdb32a248a10b9a9879e6ceb9d45dee2d75f383"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.i686-linux-gnu.tar.gz"
[[mpv]]
arch = "i686"
git-tree-sha1 = "7d13c2639d8587c1d109f130d15a40d094d77121"
libc = "musl"
os = "linux"

    [[mpv.download]]
    sha256 = "170b08b12014027f880a37c585d9ea4e65bfb8cb2ae0967854e9e3e8beb61456"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.i686-linux-musl.tar.gz"
[[mpv]]
arch = "i686"
git-tree-sha1 = "0e96fb85361a8668415c72cf3cc43769d193dad4"
os = "windows"

    [[mpv.download]]
    sha256 = "971056049310a4ae1ac6af43719c6e8f9bbb0de1b922e8716579de6f0f1a65b0"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.i686-w64-mingw32.tar.gz"
[[mpv]]
arch = "powerpc64le"
git-tree-sha1 = "900ec3648b76035afd35ba84b4c8a99a244ae6b1"
libc = "glibc"
os = "linux"

    [[mpv.download]]
    sha256 = "99b74b2e56a041c91e827a822d63145499588fe364f7a5b448b99039e1ea0ec2"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.powerpc64le-linux-gnu.tar.gz"
[[mpv]]
arch = "x86_64"
git-tree-sha1 = "e3ca0a2a78105af60eda0f8ee96eeca86fda0707"
os = "macos"

    [[mpv.download]]
    sha256 = "1b7f67981680a41557ab80587c28335de9ced574393849174aba7f524962ade0"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.x86_64-apple-darwin14.tar.gz"
[[mpv]]
arch = "x86_64"
git-tree-sha1 = "ba3aeb4deb25ce8a623dbd6bfc624ccb1624c7c3"
libc = "glibc"
os = "linux"

    [[mpv.download]]
    sha256 = "50c45f3640e3c8272966ac9a0b9717aa8366f429819a04421a3f8a8b0b300b46"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.x86_64-linux-gnu.tar.gz"
[[mpv]]
arch = "x86_64"
git-tree-sha1 = "91d34e9dc94712f299fb26816df86314665f0cef"
libc = "musl"
os = "linux"

    [[mpv.download]]
    sha256 = "ea538917a30a0f37e5fd4f575e1ce88f7598eeddabb9d0388cd0fb17f0b5563c"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.x86_64-linux-musl.tar.gz"
[[mpv]]
arch = "x86_64"
git-tree-sha1 = "97a4fb6e638e8b1f5f71dc707c37d31046581cfc"
os = "windows"

    [[mpv.download]]
    sha256 = "645e5213d53e107ab083eaf4f6a401c21aede6f837347050a32353c3d71c7161"
    url = "https://github.com/JuliaBinaryWrappers/mpv_jll.jl/releases/download/mpv-v0.32.0+0/mpv.v0.32.0.x86_64-w64-mingw32.tar.gz"
